### ISSUE TITLE
Double encoding throws error

### ISSUE THREAD

**Issue by arvindkumarb** [nitstorm/pyencode#1]
Hi! Here is something I encountered.

	python pyencode.py --algorithm url -n 2 "<b>testtest</b>"

	URL
	======
	URL Encode:		%3Cscript%3Ealert%281%29%3C%2Fscript%3E
	Traceback (most recent call last):
	  File "pyencode.py", line 215, in <module>
		for time in xrange(2, args.number+1):
	TypeError: can only concatenate list (not "int") to list

**Comment by nitstorm** [comment]
Thanks @arvindkumarb . This has been fixed in [v0.2](https://github.com/nitstorm/pyencode/releases/tag/v0.2).
