### ISSUE TITLE
Not specifying the n parameter throws an error

### ISSUE THREAD

**Issue by ranjanrj** [nitstorm/pyencode#2]
$ python pyencode.py hi
	Traceback (most recent call last):
	  File "pyencode.py", line 182, in <module>
	    args.number = args.number[0]
	TypeError: 'int' object has no attribute '__getitem__'

**Comment by nitstorm** [comment]
Thank you @ranjanrj for pointing out the bug. It has been fixed in [v0.3](https://github.com/nitstorm/pyencode/releases/tag/v0.3)
